version: '3.8'
services:
  ISAAC-profile-database:
    image: mysql
    networks:
      - ISAAC-network
    ports:
      - 3306:3306
    environment:
        - MYSQL_ROOT-PASSWORD=
        - MYSQL_PASSWORD=
        - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d

networks:
  ISAAC-network: